tasks_dic = {'freesolv': ['activity'], 'esol': ['activity'], 'lipop': ['activity'], 'bace': ['activity'],
             'bbbp': ['activity'], 'hiv': ['activity'],
             'clintox1': ['FDA_APPROVED'],
             'clintox2': ['CT_TOX'],
             'sider1': ['SIDER1'],
             'sider2': ['SIDER2'],
             'sider3': ['SIDER3'],
             'sider4': ['SIDER4'],
             'sider5': ['SIDER5'],
             'sider6': ['SIDER6'],
             'sider7': ['SIDER7'],
             'sider8': ['SIDER8'],
             'sider9': ['SIDER9'],
             'sider10': ['SIDER10'],
             'sider11': ['SIDER11'],
             'sider12': ['SIDER12'],
             'sider13': ['SIDER13'],
             'sider14': ['SIDER14'],
             'sider15': ['SIDER15'],
             'sider16': ['SIDER16'],
             'sider17': ['SIDER17'],
             'sider18': ['SIDER18'],
             'sider19': ['SIDER19'],
             'sider20': ['SIDER20'],
             'sider21': ['SIDER21'],
             'sider22': ['SIDER22'],
             'sider23': ['SIDER23'],
             'sider24': ['SIDER24'],
             'sider25': ['SIDER25'],
             'sider26': ['SIDER26'],
             'sider27': ['SIDER27'],
             'tox211': ['NR-AR'],
             'tox212': ['NR-AR-LBD'],
             'tox213': ['NR-AhR'],
             'tox214': ['NR-Aromatase'],
             'tox215': ['NR-ER'],
             'tox216': ['NR-ER-LBD'],
             'tox217': ['NR-PPAR-gamma'],
             'tox218': ['SR-ARE'],
             'tox219': ['SR-ATAD5'],
             'tox2110': ['SR-HSE'],
             'tox2111': ['SR-MMP'],
             'tox2112': ['SR-p53'],
             'muv1': ['MUV-466'],
             'muv2': ['MUV-548'],
             'muv3': ['MUV-600'],
             'muv4': ['MUV-644'],
             'muv5': ['MUV-652'],
             'muv6': ['MUV-689'],
             'muv7': ['MUV-692'],
             'muv8': ['MUV-712'],
             'muv9': ['MUV-713'],
             'muv10': ['MUV-733'],
             'muv11': ['MUV-737'],
             'muv12': ['MUV-810'],
             'muv13': ['MUV-832'],
             'muv14': ['MUV-846'],
             'muv15': ['MUV-852'],
             'muv16': ['MUV-858'],
             'muv17': ['MUV-859'],
             'toxcast1': ['ACEA_T47D_80hr_Negative'],
             'toxcast2': ['ACEA_T47D_80hr_Positive'],
             'toxcast3': ['APR_HepG2_CellCycleArrest_24h_dn'],
             'toxcast4': ['APR_HepG2_CellCycleArrest_72h_dn'],
             'toxcast5': ['APR_HepG2_CellLoss_24h_dn'],
             'toxcast6': ['APR_HepG2_CellLoss_72h_dn'],
             'toxcast7': ['APR_HepG2_MicrotubuleCSK_72h_up'],
             'toxcast8': ['APR_HepG2_MitoMass_24h_dn'],
             'toxcast9': ['APR_HepG2_MitoMass_72h_dn'],
             'toxcast10': ['APR_HepG2_MitoMembPot_24h_dn'],
             'toxcast11': ['APR_HepG2_MitoMembPot_72h_dn'],
             'toxcast12': ['APR_HepG2_MitoticArrest_24h_up'],
             'toxcast13': ['APR_HepG2_MitoticArrest_72h_up'],
             'toxcast14': ['APR_HepG2_OxidativeStress_24h_up'],
             'toxcast15': ['APR_HepG2_OxidativeStress_72h_up'],
             'toxcast16': ['APR_HepG2_StressKinase_72h_up'],
             'toxcast17': ['APR_HepG2_p53Act_24h_up'],
             'toxcast18': ['APR_HepG2_p53Act_72h_up'],
             'toxcast19': ['ATG_AP_1_CIS_up'],
             'toxcast20': ['ATG_Ahr_CIS_up'],
             'toxcast21': ['ATG_BRE_CIS_up'],
             'toxcast22': ['ATG_CMV_CIS_up'],
             'toxcast23': ['ATG_CRE_CIS_up'],
             'toxcast24': ['ATG_DR4_LXR_CIS_dn'],
             'toxcast25': ['ATG_DR5_CIS_up'],
             'toxcast26': ['ATG_EGR_CIS_up'],
             'toxcast27': ['ATG_ERE_CIS_up'],
             'toxcast28': ['ATG_ERa_TRANS_up'],
             'toxcast29': ['ATG_E_Box_CIS_dn'],
             'toxcast30': ['ATG_HIF1a_CIS_up'],
             'toxcast31': ['ATG_HSE_CIS_up'],
             'toxcast32': ['ATG_IR1_CIS_dn'],
             'toxcast33': ['ATG_ISRE_CIS_dn'],
             'toxcast34': ['ATG_MRE_CIS_up'],
             'toxcast35': ['ATG_NRF2_ARE_CIS_up'],
             'toxcast36': ['ATG_Oct_MLP_CIS_up'],
             'toxcast37': ['ATG_PBREM_CIS_up'],
             'toxcast38': ['ATG_PPARg_TRANS_up'],
             'toxcast39': ['ATG_PPRE_CIS_up'],
             'toxcast40': ['ATG_PXRE_CIS_dn'],
             'toxcast41': ['ATG_PXRE_CIS_up'],
             'toxcast42': ['ATG_PXR_TRANS_up'],
             'toxcast43': ['ATG_Pax6_CIS_up'],
             'toxcast44': ['ATG_RORE_CIS_up'],
             'toxcast45': ['ATG_RXRb_TRANS_up'],
             'toxcast46': ['ATG_SREBP_CIS_up'],
             'toxcast47': ['ATG_Sp1_CIS_up'],
             'toxcast48': ['ATG_TCF_b_cat_CIS_dn'],
             'toxcast49': ['ATG_VDRE_CIS_up'],
             'toxcast50': ['ATG_Xbp1_CIS_up'],
             'toxcast51': ['ATG_p53_CIS_dn'],
             'toxcast52': ['BSK_3C_Eselectin_down'],
             'toxcast53': ['BSK_3C_HLADR_down'],
             'toxcast54': ['BSK_3C_ICAM1_down'],
             'toxcast55': ['BSK_3C_IL8_down'],
             'toxcast56': ['BSK_3C_MCP1_down'],
             'toxcast57': ['BSK_3C_MIG_down'],
             'toxcast58': ['BSK_3C_Proliferation_down'],
             'toxcast59': ['BSK_3C_SRB_down'],
             'toxcast60': ['BSK_3C_Thrombomodulin_up'],
             'toxcast61': ['BSK_3C_TissueFactor_down'],
             'toxcast62': ['BSK_3C_VCAM1_down'],
             'toxcast63': ['BSK_3C_Vis_down'],
             'toxcast64': ['BSK_3C_uPAR_down'],
             'toxcast65': ['BSK_4H_Eotaxin3_down'],
             'toxcast66': ['BSK_4H_MCP1_down'],
             'toxcast67': ['BSK_4H_Pselectin_down'],
             'toxcast68': ['BSK_4H_SRB_down'],
             'toxcast69': ['BSK_4H_VCAM1_down'],
             'toxcast70': ['BSK_4H_VEGFRII_down'],
             'toxcast71': ['BSK_4H_uPAR_down'],
             'toxcast72': ['BSK_BE3C_HLADR_down'],
             'toxcast73': ['BSK_BE3C_IL1a_down'],
             'toxcast74': ['BSK_BE3C_IP10_down'],
             'toxcast75': ['BSK_BE3C_MIG_down'],
             'toxcast76': ['BSK_BE3C_MMP1_down'],
             'toxcast77': ['BSK_BE3C_MMP1_up'],
             'toxcast78': ['BSK_BE3C_PAI1_down'],
             'toxcast79': ['BSK_BE3C_SRB_down'],
             'toxcast80': ['BSK_BE3C_TGFb1_down'],
             'toxcast81': ['BSK_BE3C_tPA_down'],
             'toxcast82': ['BSK_BE3C_uPAR_down'],
             'toxcast83': ['BSK_BE3C_uPA_down'],
             'toxcast84': ['BSK_CASM3C_HLADR_down'],
             'toxcast85': ['BSK_CASM3C_IL6_down'],
             'toxcast86': ['BSK_CASM3C_IL8_down'],
             'toxcast87': ['BSK_CASM3C_LDLR_down'],
             'toxcast88': ['BSK_CASM3C_MCP1_down'],
             'toxcast89': ['BSK_CASM3C_MCSF_down'],
             'toxcast90': ['BSK_CASM3C_MIG_down'],
             'toxcast91': ['BSK_CASM3C_Proliferation_down'],
             'toxcast92': ['BSK_CASM3C_SAA_down'],
             'toxcast93': ['BSK_CASM3C_SRB_down'],
             'toxcast94': ['BSK_CASM3C_Thrombomodulin_up'],
             'toxcast95': ['BSK_CASM3C_TissueFactor_down'],
             'toxcast96': ['BSK_CASM3C_VCAM1_down'],
             'toxcast97': ['BSK_CASM3C_uPAR_down'],
             'toxcast98': ['BSK_KF3CT_ICAM1_down'],
             'toxcast99': ['BSK_KF3CT_IL1a_down'],
             'toxcast100': ['BSK_KF3CT_IP10_down'],
             'toxcast101': ['BSK_KF3CT_MCP1_down'],
             'toxcast102': ['BSK_KF3CT_MMP9_down'],
             'toxcast103': ['BSK_KF3CT_SRB_down'],
             'toxcast104': ['BSK_KF3CT_TGFb1_down'],
             'toxcast105': ['BSK_KF3CT_TIMP2_down'],
             'toxcast106': ['BSK_KF3CT_uPA_down'],
             'toxcast107': ['BSK_LPS_CD40_down'],
             'toxcast108': ['BSK_LPS_Eselectin_down'],
             'toxcast109': ['BSK_LPS_IL1a_down'],
             'toxcast110': ['BSK_LPS_IL8_down'],
             'toxcast111': ['BSK_LPS_MCP1_down'],
             'toxcast112': ['BSK_LPS_MCSF_down'],
             'toxcast113': ['BSK_LPS_PGE2_down'],
             'toxcast114': ['BSK_LPS_SRB_down'],
             'toxcast115': ['BSK_LPS_TNFa_down'],
             'toxcast116': ['BSK_LPS_TissueFactor_down'],
             'toxcast117': ['BSK_LPS_VCAM1_down'],
             'toxcast118': ['BSK_SAg_CD38_down'],
             'toxcast119': ['BSK_SAg_CD40_down'],
             'toxcast120': ['BSK_SAg_CD69_down'],
             'toxcast121': ['BSK_SAg_Eselectin_down'],
             'toxcast122': ['BSK_SAg_IL8_down'],
             'toxcast123': ['BSK_SAg_MCP1_down'],
             'toxcast124': ['BSK_SAg_MIG_down'],
             'toxcast125': ['BSK_SAg_PBMCCytotoxicity_down'],
             'toxcast126': ['BSK_SAg_Proliferation_down'],
             'toxcast127': ['BSK_SAg_SRB_down'],
             'toxcast128': ['BSK_hDFCGF_CollagenIII_down'],
             'toxcast129': ['BSK_hDFCGF_IL8_down'],
             'toxcast130': ['BSK_hDFCGF_IP10_down'],
             'toxcast131': ['BSK_hDFCGF_MCSF_down'],
             'toxcast132': ['BSK_hDFCGF_MIG_down'],
             'toxcast133': ['BSK_hDFCGF_MMP1_down'],
             'toxcast134': ['BSK_hDFCGF_PAI1_down'],
             'toxcast135': ['BSK_hDFCGF_Proliferation_down'],
             'toxcast136': ['BSK_hDFCGF_SRB_down'],
             'toxcast137': ['BSK_hDFCGF_TIMP1_down'],
             'toxcast138': ['BSK_hDFCGF_VCAM1_down'],
             'toxcast139': ['CEETOX_H295R_11DCORT_dn'],
             'toxcast140': ['CEETOX_H295R_ANDR_dn'],
             'toxcast141': ['CEETOX_H295R_CORTISOL_dn'],
             'toxcast142': ['CEETOX_H295R_ESTRONE_dn'],
             'toxcast143': ['CEETOX_H295R_ESTRONE_up'],
             'toxcast144': ['NHEERL_ZF_144hpf_TERATOSCORE_up'],
             'toxcast145': ['NVS_NR_bER'],
             'toxcast146': ['NVS_NR_hER'],
             'toxcast147': ['NVS_NR_hPPARg'],
             'toxcast148': ['NVS_NR_hPXR'],
             'toxcast149': ['NVS_NR_mERa'],
             'toxcast150': ['OT_AR_ARSRC1_0960'],
             'toxcast151': ['OT_ER_ERaERb_0480'],
             'toxcast152': ['OT_ER_ERaERb_1440'],
             'toxcast153': ['OT_ER_ERbERb_0480'],
             'toxcast154': ['OT_ER_ERbERb_1440'],
             'toxcast155': ['OT_ERa_EREGFP_0120'],
             'toxcast156': ['OT_FXR_FXRSRC1_0480'],
             'toxcast157': ['OT_NURR1_NURR1RXRa_0480'],
             'toxcast158': ['TOX21_ARE_BLA_agonist_ratio'],
             'toxcast159': ['TOX21_AR_BLA_Antagonist_ratio'],
             'toxcast160': ['TOX21_AR_LUC_MDAKB2_Antagonist'],
             'toxcast161': ['TOX21_AR_LUC_MDAKB2_Antagonist2'],
             'toxcast162': ['TOX21_AhR_LUC_Agonist'],
             'toxcast163': ['TOX21_Aromatase_Inhibition'],
             'toxcast164': ['TOX21_ERa_BLA_Antagonist_ratio'],
             'toxcast165': ['TOX21_ERa_LUC_BG1_Agonist'],
             'toxcast166': ['TOX21_FXR_BLA_antagonist_ratio'],
             'toxcast167': ['TOX21_MMP_ratio_down'],
             'toxcast168': ['TOX21_TR_LUC_GH3_Antagonist'],
             'toxcast169': ['TOX21_p53_BLA_p1_ratio'],
             'toxcast170': ['TOX21_p53_BLA_p2_ch2'],
             'toxcast171': ['TOX21_p53_BLA_p2_ratio'],
             'toxcast172': ['TOX21_p53_BLA_p2_viability'],
             'toxcast173': ['TOX21_p53_BLA_p3_ratio'],
             'toxcast174': ['TOX21_p53_BLA_p4_ratio'],
             'toxcast175': ['TOX21_p53_BLA_p5_ratio'],
             'toxcast176': ['Tanguay_ZF_120hpf_AXIS_up'],
             'toxcast177': ['Tanguay_ZF_120hpf_ActivityScore'],
             'toxcast178': ['Tanguay_ZF_120hpf_JAW_up'],
             'toxcast179': ['Tanguay_ZF_120hpf_MORT_up'],
             'toxcast180': ['Tanguay_ZF_120hpf_PE_up'],
             'toxcast181': ['Tanguay_ZF_120hpf_SNOU_up'],
             'toxcast182': ['Tanguay_ZF_120hpf_YSE_up'],
             'clintox': ['FDA_APPROVED', 'CT_TOX'],
             'sider': ['SIDER1', 'SIDER2', 'SIDER3', 'SIDER4', 'SIDER5', 'SIDER6', 'SIDER7', 'SIDER8', 'SIDER9',
                       'SIDER10', 'SIDER11', 'SIDER12', 'SIDER13', 'SIDER14', 'SIDER15', 'SIDER16', 'SIDER17',
                       'SIDER18', 'SIDER19', 'SIDER20', 'SIDER21', 'SIDER22', 'SIDER23', 'SIDER24', 'SIDER25',
                       'SIDER26', 'SIDER27'],
             'tox21': ['NR-AR', 'NR-AR-LBD', 'NR-AhR', 'NR-Aromatase', 'NR-ER', 'NR-ER-LBD', 'NR-PPAR-gamma', 'SR-ARE',
                       'SR-ATAD5', 'SR-HSE', 'SR-MMP', 'SR-p53'],
             'muv': [
                 "MUV-466", "MUV-548", "MUV-600", "MUV-644", "MUV-652", "MUV-689", "MUV-692", "MUV-712", "MUV-713",
                 "MUV-733", "MUV-737", "MUV-810", "MUV-832", "MUV-846", "MUV-852", "MUV-858", "MUV-859"
             ],
             'toxcast': ['ACEA_T47D_80hr_Negative', 'ACEA_T47D_80hr_Positive',
                         'APR_HepG2_CellCycleArrest_24h_dn',
                         'APR_HepG2_CellCycleArrest_72h_dn', 'APR_HepG2_CellLoss_24h_dn',
                         'APR_HepG2_CellLoss_72h_dn', 'APR_HepG2_MicrotubuleCSK_72h_up',
                         'APR_HepG2_MitoMass_24h_dn', 'APR_HepG2_MitoMass_72h_dn',
                         'APR_HepG2_MitoMembPot_24h_dn', 'APR_HepG2_MitoMembPot_72h_dn',
                         'APR_HepG2_MitoticArrest_24h_up', 'APR_HepG2_MitoticArrest_72h_up',
                         'APR_HepG2_OxidativeStress_24h_up',
                         'APR_HepG2_OxidativeStress_72h_up',
                         'APR_HepG2_StressKinase_72h_up', 'APR_HepG2_p53Act_24h_up',
                         'APR_HepG2_p53Act_72h_up', 'ATG_AP_1_CIS_up', 'ATG_Ahr_CIS_up',
                         'ATG_BRE_CIS_up', 'ATG_CMV_CIS_up', 'ATG_CRE_CIS_up',
                         'ATG_DR4_LXR_CIS_dn', 'ATG_DR5_CIS_up', 'ATG_EGR_CIS_up',
                         'ATG_ERE_CIS_up', 'ATG_ERa_TRANS_up', 'ATG_E_Box_CIS_dn',
                         'ATG_HIF1a_CIS_up', 'ATG_HSE_CIS_up', 'ATG_IR1_CIS_dn',
                         'ATG_ISRE_CIS_dn', 'ATG_MRE_CIS_up', 'ATG_NRF2_ARE_CIS_up',
                         'ATG_Oct_MLP_CIS_up', 'ATG_PBREM_CIS_up', 'ATG_PPARg_TRANS_up',
                         'ATG_PPRE_CIS_up', 'ATG_PXRE_CIS_dn', 'ATG_PXRE_CIS_up',
                         'ATG_PXR_TRANS_up', 'ATG_Pax6_CIS_up', 'ATG_RORE_CIS_up',
                         'ATG_RXRb_TRANS_up', 'ATG_SREBP_CIS_up', 'ATG_Sp1_CIS_up',
                         'ATG_TCF_b_cat_CIS_dn', 'ATG_VDRE_CIS_up', 'ATG_Xbp1_CIS_up',
                         'ATG_p53_CIS_dn', 'BSK_3C_Eselectin_down', 'BSK_3C_HLADR_down',
                         'BSK_3C_ICAM1_down', 'BSK_3C_IL8_down', 'BSK_3C_MCP1_down',
                         'BSK_3C_MIG_down', 'BSK_3C_Proliferation_down', 'BSK_3C_SRB_down',
                         'BSK_3C_Thrombomodulin_up', 'BSK_3C_TissueFactor_down',
                         'BSK_3C_VCAM1_down', 'BSK_3C_Vis_down', 'BSK_3C_uPAR_down',
                         'BSK_4H_Eotaxin3_down', 'BSK_4H_MCP1_down',
                         'BSK_4H_Pselectin_down', 'BSK_4H_SRB_down', 'BSK_4H_VCAM1_down',
                         'BSK_4H_VEGFRII_down', 'BSK_4H_uPAR_down', 'BSK_BE3C_HLADR_down',
                         'BSK_BE3C_IL1a_down', 'BSK_BE3C_IP10_down', 'BSK_BE3C_MIG_down',
                         'BSK_BE3C_MMP1_down', 'BSK_BE3C_MMP1_up', 'BSK_BE3C_PAI1_down',
                         'BSK_BE3C_SRB_down', 'BSK_BE3C_TGFb1_down', 'BSK_BE3C_tPA_down',
                         'BSK_BE3C_uPAR_down', 'BSK_BE3C_uPA_down', 'BSK_CASM3C_HLADR_down',
                         'BSK_CASM3C_IL6_down', 'BSK_CASM3C_IL8_down',
                         'BSK_CASM3C_LDLR_down', 'BSK_CASM3C_MCP1_down',
                         'BSK_CASM3C_MCSF_down', 'BSK_CASM3C_MIG_down',
                         'BSK_CASM3C_Proliferation_down', 'BSK_CASM3C_SAA_down',
                         'BSK_CASM3C_SRB_down', 'BSK_CASM3C_Thrombomodulin_up',
                         'BSK_CASM3C_TissueFactor_down', 'BSK_CASM3C_VCAM1_down',
                         'BSK_CASM3C_uPAR_down', 'BSK_KF3CT_ICAM1_down',
                         'BSK_KF3CT_IL1a_down', 'BSK_KF3CT_IP10_down',
                         'BSK_KF3CT_MCP1_down', 'BSK_KF3CT_MMP9_down', 'BSK_KF3CT_SRB_down',
                         'BSK_KF3CT_TGFb1_down', 'BSK_KF3CT_TIMP2_down',
                         'BSK_KF3CT_uPA_down', 'BSK_LPS_CD40_down',
                         'BSK_LPS_Eselectin_down', 'BSK_LPS_IL1a_down', 'BSK_LPS_IL8_down',
                         'BSK_LPS_MCP1_down', 'BSK_LPS_MCSF_down', 'BSK_LPS_PGE2_down',
                         'BSK_LPS_SRB_down', 'BSK_LPS_TNFa_down',
                         'BSK_LPS_TissueFactor_down', 'BSK_LPS_VCAM1_down',
                         'BSK_SAg_CD38_down', 'BSK_SAg_CD40_down', 'BSK_SAg_CD69_down',
                         'BSK_SAg_Eselectin_down', 'BSK_SAg_IL8_down', 'BSK_SAg_MCP1_down',
                         'BSK_SAg_MIG_down', 'BSK_SAg_PBMCCytotoxicity_down',
                         'BSK_SAg_Proliferation_down', 'BSK_SAg_SRB_down',
                         'BSK_hDFCGF_CollagenIII_down', 'BSK_hDFCGF_IL8_down',
                         'BSK_hDFCGF_IP10_down', 'BSK_hDFCGF_MCSF_down',
                         'BSK_hDFCGF_MIG_down', 'BSK_hDFCGF_MMP1_down',
                         'BSK_hDFCGF_PAI1_down', 'BSK_hDFCGF_Proliferation_down',
                         'BSK_hDFCGF_SRB_down', 'BSK_hDFCGF_TIMP1_down',
                         'BSK_hDFCGF_VCAM1_down', 'CEETOX_H295R_11DCORT_dn',
                         'CEETOX_H295R_ANDR_dn', 'CEETOX_H295R_CORTISOL_dn',
                         'CEETOX_H295R_ESTRONE_dn', 'CEETOX_H295R_ESTRONE_up',
                         'NHEERL_ZF_144hpf_TERATOSCORE_up', 'NVS_NR_bER', 'NVS_NR_hER',
                         'NVS_NR_hPPARg', 'NVS_NR_hPXR', 'NVS_NR_mERa', 'OT_AR_ARSRC1_0960',
                         'OT_ER_ERaERb_0480', 'OT_ER_ERaERb_1440', 'OT_ER_ERbERb_0480',
                         'OT_ER_ERbERb_1440', 'OT_ERa_EREGFP_0120', 'OT_FXR_FXRSRC1_0480',
                         'OT_NURR1_NURR1RXRa_0480', 'TOX21_ARE_BLA_agonist_ratio',
                         'TOX21_AR_BLA_Antagonist_ratio', 'TOX21_AR_LUC_MDAKB2_Antagonist',
                         'TOX21_AR_LUC_MDAKB2_Antagonist2', 'TOX21_AhR_LUC_Agonist',
                         'TOX21_Aromatase_Inhibition', 'TOX21_ERa_BLA_Antagonist_ratio',
                         'TOX21_ERa_LUC_BG1_Agonist', 'TOX21_FXR_BLA_antagonist_ratio',
                         'TOX21_MMP_ratio_down', 'TOX21_TR_LUC_GH3_Antagonist',
                         'TOX21_p53_BLA_p1_ratio', 'TOX21_p53_BLA_p2_ch2',
                         'TOX21_p53_BLA_p2_ratio', 'TOX21_p53_BLA_p2_viability',
                         'TOX21_p53_BLA_p3_ratio', 'TOX21_p53_BLA_p4_ratio',
                         'TOX21_p53_BLA_p5_ratio', 'Tanguay_ZF_120hpf_AXIS_up',
                         'Tanguay_ZF_120hpf_ActivityScore', 'Tanguay_ZF_120hpf_JAW_up',
                         'Tanguay_ZF_120hpf_MORT_up', 'Tanguay_ZF_120hpf_PE_up',
                         'Tanguay_ZF_120hpf_SNOU_up', 'Tanguay_ZF_120hpf_YSE_up']}
